style: fix yml files

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,38 +13,38 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-    
+
     strategy:
       fail-fast: false
       matrix:
         dotnet-version: [ '2.0.x', '7.0.x' ]
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v3
 
-    - name: Setup .Net ${{ matrix.dotnet-version }}
-      uses: actions/setup-dotnet@v3
-      with:
-        dotnet-version: ${{ matrix.dotnet-version }}
-    
-    - name: Dotnet Info
-      run: dotnet --info
+      - name: Setup .Net ${{ matrix.dotnet-version }}
+        uses: actions/setup-dotnet@v3
+        with:
+          dotnet-version: ${{ matrix.dotnet-version }}
 
-    - name: Restore dependencies
-      run: dotnet restore "${{ env.sln-path }}"
+      - name: .Net Info
+        run: dotnet --info
 
-    - name: Build debug
-      run: dotnet build "${{ env.sln-path }}" --no-restore
+      - name: Restore dependencies
+        run: dotnet restore "${{ env.sln-path }}"
 
-    - name: Test
-      run: dotnet test "${{ env.sln-path }}" --no-build --logger "trx;LogFileName=test-results.trx" || true
+      - name: Build debug
+        run: dotnet build "${{ env.sln-path }}" --no-restore
 
-    #- name: Test Report
-    #  uses: dorny/test-reporter@v1
-    #  if: always()
-    #  with:
-    #    name: Tests ${{ matrix.dotnet-version }}
-    #    path: "**/test-results.trx"                            
-    #    reporter: dotnet-trx
-    #    fail-on-error: true
+      - name: Test
+        run: dotnet test "${{ env.sln-path }}" --no-build --logger "trx;LogFileName=test-results.trx" || true
+
+      # - name: Test Report
+      #   uses: dorny/test-reporter@v1
+      #   if: always()
+      #   with:
+      #     name: Tests ${{ matrix.dotnet-version }}
+      #     path: "**/test-results.trx"
+      #     reporter: dotnet-trx
+      #     fail-on-error: true
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -8,58 +8,58 @@ on:
   push:
     tags:
       - "v*.*.*"
-      
+
 jobs:
   build:
     runs-on: ubuntu-latest
-    
+
     strategy:
       matrix:
         dotnet-version: [ '2.0.x', '7.0.x' ]
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v3
 
-    - name: Setup .Net ${{ matrix.dotnet-version }}
-      uses: actions/setup-dotnet@v3
-      with:
-        dotnet-version: ${{ matrix.dotnet-version }}
-    
-    - name: Dotnet Info
-      run: dotnet --info
+      - name: Setup .Net ${{ matrix.dotnet-version }}
+        uses: actions/setup-dotnet@v3
+        with:
+          dotnet-version: ${{ matrix.dotnet-version }}
 
-    - name: Restore
-      run: dotnet restore "${{ env.sln-path }}"
+      - name: .Net Info
+        run: dotnet --info
 
-    - name: Publish
-      run: dotnet publish "${{ env.sln-path }}" -c Release -o "${{ env.build-dir }}" --no-restore
+      - name: Restore
+        run: dotnet restore "${{ env.sln-path }}"
 
-    - name: Test
-      run: dotnet test "${{ env.sln-path }}" --no-build --logger "trx;LogFileName=test-results.trx" || true
+      - name: Publish
+        run: dotnet publish "${{ env.sln-path }}" -c Release -o "${{ env.build-dir }}" --no-restore
 
-    #- name: Test Report
-    #  uses: dorny/test-reporter@v1
-    #  if: always()
-    #  with:
-    #    name: Tests ${{ matrix.dotnet-version }}
-    #    path: "**/test-results.trx"                            
-    #    reporter: dotnet-trx
-    #    fail-on-error: true
-    
-    - name: Upload artifact
-      uses: actions/upload-artifact@v3
-      with:
-        name: binaries
-        path: "${{ env.build-dir }}"
-        retention-days: 90
+      - name: Test
+        run: dotnet test "${{ env.sln-path }}" --no-build --logger "trx;LogFileName=test-results.trx" || true
+
+      # - name: Test Report
+      #   uses: dorny/test-reporter@v1
+      #   if: always()
+      #   with:
+      #     name: Tests ${{ matrix.dotnet-version }}
+      #     path: "**/test-results.trx"
+      #     reporter: dotnet-trx
+      #     fail-on-error: true
+
+      - name: Upload artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: binaries
+          path: "${{ env.build-dir }}"
+          retention-days: 90
 
   release:
     name: Create Release
     runs-on: ubuntu-latest
     needs: [ build ]
     env:
-      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     steps:
       - name: Download build artifact
